name: Scrape Listings
#clear this line and delete the # to resume
#on:
#  schedule:
#    - cron: "0 3 * * *" # once daily at 3:00 AM (UTC)
#  workflow_dispatch:     # allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install puppeteer fs-extra

      - name: Run scraper
        run: node scrape.js

      - name: Commit listings.json
        run: |
          git config user.name "Combloc Bot"
          git config user.email "bot@comblocmarket.com"
          git add listings.json
          git commit -m "Update listings.json" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
